<?php
return
[
    "mataPelajaran_x"=>[
        "x"=>[
            "seni"=>"kelasX",
            "informatika"=>"kelasX"
        ]
        ],
    "mataPelajaran_xi"=>[
        "xi"=>[
            "pkk"=>"kelasXI",
            "webDev"=>"kelasXI"
        ]
    ]
];
